### ISSUE TITLE
[TangoEnSkai] 1차 미션 개인 TODO list 

### ISSUE THREAD

**Issue by TangoEnSkai** [ultimate-go-korean/translation#35]
NOTE: this is a personal note, DO NOT EDIT.

TODO: summarise what do to and make a TODO list

- [x] check out the first given mission
- [x] check several examples 
  - [x] https://github.com/ultimate-go-korean/translation/blob/main/101-114/101-114.md
  - [x] https://github.com/ultimate-go-korean/translation/blob/main/89-101/89-101.md
- [x] understand how to employ `prettier`
- [x] make PR(s) with original script 
  - [x] Store and retrieve values from a context 164 #36 
  - [x] WithCancel 166 #39 
  - [x] WithDeadline 168 #40 
  - [x]  WithTimeout 169 #41
  - [x] Request/Response 171 #42 
- [x] start review processes /. request sent
  - [x] Store and retrieve values from a context 164 #36 
  - [x] WithCancel 166 #39 
  - [x] WithDeadline 168 #40 
  - [x]  WithTimeout 169 #41
  - [x] Request/Response 171 #42 
- [x] merge the PR & close this issue.
  - [ ] Store and retrieve values from a context 164 #36 
  - [x] WithCancel 166 #39 
  - [x] WithDeadline 168 #40 
  - [x]  WithTimeout 169 #41
  - [x] Request/Response 171 #42 
- [x] final check and finish the 1st mission. 

---

Reference below

# 1차 미션 - 영문 Markdown을 완성하라

이번 주말까지 영문 Markdown을 PR(Pull Request) 하는 것을 1차 미션으로 합니다

이미 Approve 된 분들의 결과물을 참고하십시오

- https://github.com/ultimate-go-korean/translation/blob/main/101-114/101-114.md

- https://github.com/ultimate-go-korean/translation/blob/main/89-101/89-101.md

- 이 예제는 백틱(``) 을 잘 활용하여 함수나 구조체 이름을 두드러지게 표시한 점을 참고하십시오

 

1차 미션
 

1) 범위 별 번역 담당자와 리뷰 담당자가 정리되었습니다. 

assignment.md: https://bit.ly/36S9t6N
2) 번역 담당자는 금주 내로 영문 Markdown 작성 후 PR 합니다. 그러면 자동으로 CODEOWNERS 에게 리뷰 요청이 갑니다. 

CODEOWNERS: https://bit.ly/34D8c0D
3) 해당 범위의 리뷰어들이 코멘트 및 수정제안을 합니다. 

- 담당 리뷰어가 아니어도 PR 리뷰 주시면 도움이 됩니다. 

GitHub 내에서 수정 제안 만들기, batch로 수정 제안을 일괄 commit 하기 등을 연습하세요. 
4) 리뷰가 완료되면 squash and merge 하는 것으로 하겠습니다. 

Approval 충족 조건은 2명으로 상향 조정 합니다. 조금 느려도 충실히 리뷰하려 합니다
꼼꼼한 리뷰는 서로에게 신뢰와 의지가 됩니다.
 

번역자의 작업 과정
 

1) 로컬 PC에 clone 합니다. 

2) main 브랜치를 최신으로 유지한 상태에서 자신만의 브랜치를 땁니다.

ex. git checkout - b eng-markdown/20-37
3) PDF 파일의 해당 범위를 복사하여 붙여 넣고, Markdown에 맞게 다듬습니다. 

./diagrams 폴더에 다이어그램 이미지들이 있으니 넣어야 하는 분들은 Markdown 에 추가하세요
4) git add 와 commit을 마치시고 PR 하시면 됩니다.

조금 더 나아가 배워보고 싶으신 분은 GitHub CLI 의 gh pr create 명령을 써보세요
 

PDF 복사, 붙여 넣기의 주요 오류 및 참고 사항
 

1) 코드 블럭은 ```go 와 ``` 로 감싸세요.  

2) 코드내의 들여쓰기가 안맞는 경우가 있습니다. 스페이스 4개로 통일하여 맞추세요

3) 배열의 대괄호 같은 부분, 함수의 파라미터가 들어가는 소괄호 부분 등에 스페이스가 들어갑니다. 제거하세요

4) 코멘트가 여러 줄 일 때에 맨 위 한 줄만 코멘트 되는 경우가 있습니다. 한 줄로 만들거나 줄마다 코멘트 해주세요

 

 

 

 

 

Welcome to posts
Tell me more • I’ll work it out

**Comment by nicewook** [comment]
와우 멋지게 진행하셨네요. 체크박스 테스트 해봅니다

파란색 체크박스는 어떻게 하신건가요? 

- [ ] 테스트
- [x] 테스트

**Comment by TangoEnSkai** [comment]
> 와우 멋지게 진행하셨네요. 체크박스 테스트 해봅니다
> 
> * [ ]  테스트
> * [x]  테스트

감사합니다. 습관이되서 그런지 이렇게 적지 않으면 까먹습니다. 😅

**Comment by TangoEnSkai** [comment]
리뷰 완료후 모두 @nicewook 님께서 친절하게 merge해 주셨으므로 이슈를 닫습니다.
